### ISSUE TITLE
Possible issue with MRP chat names code

### ISSUE THREAD

**Issue by Katoriehooves** [Ellypse/MyRolePlay#2]
I've received several reports over the past 24 hours from MRP specific users being unable to see RP names in chat. (Say/Emote/Yell etc). I've tested this with a friend (Both using MRP) and while my character's name did appear in their msp.char field NA, it's not carrying over to the chat itself.

**Comment by Solanya** [comment]
Ellypse doesn't want me to edit files directly on Github so he can modify by himself `ChatName.lua` on line 23 to replace `msp.char[ sender ].time.NA` with `msp.char[ sender ].field.NA`.
We're still investigating how this code even worked before.
