### ISSUE TITLE
Enemy faction tooltips not loading, also /mrp Show doesn't work on targets

### ISSUE THREAD

**Issue by Katoriehooves** [Ellypse/MyRolePlay#5]
The UnitIsFriend conditional in mrp_MouseoverEvent() is preventing cross faction tooltip support. It appears in mrp:Show() as well, preventing loading profiles of the player's target.

**Comment by Ellypse** [comment]
Note: We should just do a "Find all" on `UnitIsFriend` on MRP.

**Comment by Katoriehooves** [comment]
I already did, those are the only two instances of it.
